### ISSUE TITLE
No 'ok' member in app.scripts.helpers.workspace

### ISSUE THREAD

**Issue by jeremydouglass** [whatevery1says/we1s-wms#15]
While linting I wasn't sure how to correct this -- it wasn't immediately clear what the intention was.

```
************* Module app.scripts.helpers.workspace
app/scripts/helpers/workspace.py:78:32: E1101: Instance of 'LookupDict' has no 'ok' member (no-member)
app/scripts/helpers/workspace.py:98:40: E1101: Instance of 'LookupDict' has no 'ok' member (no-member)

```

**Comment by scottkleinman** [comment]
I'm not sure what is causing this particular linting error (the code worked when I tested it, though). Regardless, the Scripts module is simply a copy of an earlier version of Projects and is not yet functional. (I notice that the offending function has been removed from Projects.) So I wouldn't worry about this error. If it is causing problems, you can simply comment out the code.
