### ISSUE TITLE
floating branch monday-anando

### ISSUE THREAD

**Issue by jeremydouglass** [whatevery1says/we1s-wms#24]
There is a disconnected floating branch "monday-anando" in the repo that appears before "Initial commit"

c15c6926a5379b6839ff01fff29f7eb3e7a6c023
...
1ba28dc71e482df187cd2a12d56c7123e3069b76

Should we delete it? Is there anything that needs to be backed up for integration before we do?

**Comment by scottkleinman** [comment]
I think everything in it has been integrated, but I've downloaded a backup just in case. Go ahead and delete the branch.

**Comment by jeremydouglass** [comment]
Deleted.
